[package]
name = "resume-for-reseachers"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Ryan Reese <https://github.com/Ryan-Reese"]
license = "MIT"
description = "Made for reseachers; Written with Typst"
repository = "https://github.com/Ryan-Reese/typst-resume-template"
keywords = ["cv", "resume", "research"]
categories = ["cv"]
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
